import { CV_PRODUCT_NAME } from '@/lib/brand';

export const resumeBuilderCopy = {
  ar: {
    sections: [
      'البيانات الشخصية',
      'النبذة المهنية',
      'المهارات',
      'المشاريع',
      'الخبرات المهنية',
      'المؤهلات التعليمية',
      'الشهادات المهنية',
      'الجوائز والإنجازات',
      'الأعمال التطوعية',
      'اللغات',
    ],
    untitledResume: 'سيرة ذاتية بدون عنوان',
    templatePrefix: 'قالب',
    emailSendFailed: 'تعذر إرسال السيرة.',
    emailSentTo: 'أُرسلت إلى',
    entryEyebrow: 'سيرة ذاتية جديدة',
    entryTitle: 'كيف تفضل أن تبدأ؟',
    entryLead: 'يمكنك تغيير المسار لاحقاً دون فقدان أي معلومات.',
    recommended: 'موصى به',
    guidedTitle: 'ساعدني خطوة بخطوة',
    guidedDescription: 'نجمع معلوماتك في مراحل قصيرة، ثم نعرض السيرة كاملة للتعديل والتنسيق.',
    guidedTime: '5–8 دقائق',
    editorTitle: 'ابدأ من المحرر',
    editorDescription: 'افتح أدوات التحرير والمعاينة مباشرة إذا كان محتواك جاهزاً.',
    editorTime: 'ابدأ فوراً',
    guestEntryNote:
      'تعمل الآن كضيف. يمكنك إكمال السيرة كاملة، وستُحفظ المسودة في هذا المتصفح حتى تنشئ حساباً وتختار باقتك عند التنزيل.',
    memberEntryNote: 'يمكن للجميع بناء السيرة كاملة قبل الدفع، ويظهر اختيار الباقة فقط عند تنزيل النسخة النهائية.',
    dashboard: 'لوحة التحكم',
    platform: CV_PRODUCT_NAME,
    builder: 'صانع السيرة الذاتية',
    workspaceView: 'عرض مساحة العمل',
    content: 'المحتوى',
    customize: 'التصميم',
    preview: 'المعاينة',
    signup: 'إنشاء حساب',
    saveResume: 'حفظ السيرة الذاتية',
    cloudSaveFailed: 'تعذر الحفظ السحابي، وستتم المحاولة تلقائيًا',
    saving: 'جاري الحفظ',
    saveFailed: 'تعذر الحفظ',
    unsavedChanges: 'تغييرات غير محفوظة',
    savedAt: 'حُفظ',
    localSave: 'حفظ محلي',
    save: 'حفظ',
    resumeLanguage: 'لغة السيرة',
    arabic: 'عربي',
    downloadPdf: 'تحميل PDF',
    emailResume: 'إرسال السيرة إلى البريد',
    sendEmail: 'إرسال للبريد',
    moreTools: 'المزيد من الأدوات',
    demoData: 'بيانات تجريبية',
    clearFields: 'تفريغ الحقول',
    undoAi: 'التراجع عن تحسين AI',
    openFullEditor: 'فتح المحرر الكامل',
    receiveByEmail: 'استلام نسخة بالبريد',
    guestEmailHint: 'أدخل البريد الذي تريد استلام السيرة عليه.',
    memberEmailHint: 'اختياري: اتركه فارغاً لاستخدام بريد حسابك.',
    alternateEmail: 'بريد بديل (اختياري)',
    sending: 'جاري الإرسال',
    sendCopy: 'إرسال النسخة',
    sectionsLabel: 'الأقسام',
    sectionsHint: 'اختر القسم الذي تريد تعديله',
    resetOrder: 'استعادة الترتيب',
    pinned: 'مثبت',
    atsReady: 'جاهز لأنظمة ATS',
    atsReadyHint: 'قوالب واضحة ومتوافقة مع أنظمة التوظيف',
    completion: 'اكتمال السيرة',
    workspace: 'مساحة العمل',
    editor: 'المحرر',
    aiAssistant: 'المساعد الذكي',
    personalSectionHint: 'المعلومات الأساسية ليتواصل معك أصحاب العمل.',
    sectionHint: 'اكتب المعلومات بوضوح، وسيساعدك المساعد الذكي على تحسين الصياغة.',
    aiNotice: 'يمكنك طلب تحسين أي نص من مساعد السيرة الذاتية.',
    previous: 'السابق',
    next: 'التالي',
    finishAndSave: 'إنهاء وحفظ',
    livePreview: 'معاينة مباشرة',
    zoomOut: 'تصغير المعاينة',
    zoomIn: 'تكبير المعاينة',
    resumeColor: 'لون السيرة',
    chooseColor: 'اختيار اللون',
    font: 'الخط',
    size: 'الحجم',
    pageCount: 'عدد الصفحات',
    onePage: 'صفحة',
    twoPages: 'صفحتان',
    englishRecommendationTitle: 'تتقدم إلى جهة تستخدم الإنجليزية؟',
    englishRecommendationBody: 'أنشئ نسخة إنجليزية مهنية لزيادة التوافق مع الوصف الوظيفي وأنظمة التوظيف الدولية.',
    signupForTranslation: 'سجل لاستخدام الترجمة',
    aiTranslation: 'ترجمة بالذكاء الاصطناعي',
    overflowPrefix: 'المحتوى تجاوز مساحة',
    onePageArea: 'الصفحة الواحدة',
    twoPageArea: 'إحدى الصفحتين',
    splitPages: 'تقسيم إلى صفحتين',
    templates: ['مضغوط', 'مركزي', 'بسيط', 'خريج', 'تنفيذي'],
    fields: {
      name: ['الاسم الكامل', 'مثال: محمد أحمد'],
      headline: ['المسمى المهني', 'مثال: مدير منتجات'],
      highlights: ['مميزات مختصرة', 'خبرة 7 سنوات · قيادة فرق'],
      email: ['البريد الإلكتروني', 'you@example.com'],
      phone: ['رقم الجوال', '05xxxxxxxx'],
      link: ['رابط تواصل', 'linkedin.com/in/you'],
      city: ['المدينة، الدولة', 'الرياض، السعودية'],
      summary: ['النبذة المهنية', 'اكتب نبذة مختصرة عن خبرتك وقيمتك المهنية...'],
      skills: ['المهارات', 'اكتب مهاراتك مفصولة بفواصل...'],
      languages: ['اللغات', 'العربية — اللغة الأم\nالإنجليزية — متقدم'],
      projects: ['المشاريع', 'اسم المشروع — دورك — النتيجة...'],
      experience: ['الخبرات المهنية', 'المسمى الوظيفي — الشركة — الفترة\nالإنجازات والنتائج بالأرقام...'],
      education: ['المؤهلات التعليمية', 'الدرجة — الجامعة — سنة التخرج...'],
      certificates: ['الشهادات المهنية', 'اسم الشهادة — الجهة — السنة...'],
      achievements: ['الجوائز والإنجازات', 'الجائزة أو الإنجاز — النتيجة...'],
      volunteer: ['الأعمال التطوعية', 'الجهة — الدور — الأثر...'],
    },
  },
  en: {
    sections: [
      'Personal details',
      'Professional summary',
      'Skills',
      'Projects',
      'Professional experience',
      'Education',
      'Professional certificates',
      'Awards and achievements',
      'Volunteer work',
      'Languages',
    ],
    untitledResume: 'Untitled resume',
    templatePrefix: 'Template',
    emailSendFailed: 'Could not send the resume.',
    emailSentTo: 'Sent to',
    entryEyebrow: 'New resume',
    entryTitle: 'How would you like to start?',
    entryLead: 'You can switch workflows later without losing any information.',
    recommended: 'Recommended',
    guidedTitle: 'Guide me step by step',
    guidedDescription: 'Add your information in short stages, then review the complete resume and customize it.',
    guidedTime: '5–8 minutes',
    editorTitle: 'Start in the editor',
    editorDescription: 'Open the editing tools and live preview when your content is already prepared.',
    editorTime: 'Start immediately',
    guestEntryNote:
      'You are working as a guest. Complete the resume now; this browser keeps the draft until you create an account and choose a plan at download.',
    memberEntryNote:
      'Everyone can complete a resume before paying. Plan selection appears only when downloading the final copy.',
    dashboard: 'Dashboard',
    platform: CV_PRODUCT_NAME,
    builder: 'Resume builder',
    workspaceView: 'Workspace view',
    content: 'Content',
    customize: 'Customize',
    preview: 'Preview',
    signup: 'Create account',
    saveResume: 'Save resume',
    cloudSaveFailed: 'Cloud saving failed. We will retry automatically.',
    saving: 'Saving',
    saveFailed: 'Save failed',
    unsavedChanges: 'Unsaved changes',
    savedAt: 'Saved',
    localSave: 'Save locally',
    save: 'Save',
    resumeLanguage: 'Resume language',
    arabic: 'العربية',
    downloadPdf: 'Download PDF',
    emailResume: 'Email the resume',
    sendEmail: 'Email',
    moreTools: 'More tools',
    demoData: 'Load demo data',
    clearFields: 'Clear fields',
    undoAi: 'Undo AI improvement',
    openFullEditor: 'Open full editor',
    receiveByEmail: 'Receive a copy by email',
    guestEmailHint: 'Enter the email address where you want to receive the resume.',
    memberEmailHint: 'Optional: leave blank to use your account email.',
    alternateEmail: 'Alternate email (optional)',
    sending: 'Sending',
    sendCopy: 'Send copy',
    sectionsLabel: 'Sections',
    sectionsHint: 'Choose the section you want to edit',
    resetOrder: 'Reset order',
    pinned: 'Pinned',
    atsReady: 'ATS ready',
    atsReadyHint: 'Clear templates compatible with applicant tracking systems',
    completion: 'Resume completion',
    workspace: 'Workspace',
    editor: 'Editor',
    aiAssistant: 'AI assistant',
    personalSectionHint: 'The essential information employers use to contact you.',
    sectionHint: 'Write clearly, then use the AI assistant to strengthen the wording.',
    aiNotice: 'You can ask the resume assistant to improve any text.',
    previous: 'Previous',
    next: 'Next',
    finishAndSave: 'Finish and save',
    livePreview: 'Live preview',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    resumeColor: 'Resume color',
    chooseColor: 'Choose color',
    font: 'Font',
    size: 'Size',
    pageCount: 'Page count',
    onePage: 'One page',
    twoPages: 'Two pages',
    englishRecommendationTitle: 'Applying to an English-speaking employer?',
    englishRecommendationBody:
      'Create a professional English version for better alignment with the role and international hiring systems.',
    signupForTranslation: 'Sign up to translate',
    aiTranslation: 'Translate with AI',
    overflowPrefix: 'The content exceeds',
    onePageArea: 'the single-page limit',
    twoPageArea: 'one of the two pages',
    splitPages: 'Split into two pages',
    templates: ['Compact', 'Centered', 'Minimal', 'Graduate', 'Executive'],
    fields: {
      name: ['Full name', 'Example: Mohammed Ahmed'],
      headline: ['Professional title', 'Example: Product Manager'],
      highlights: ['Career highlights', '7 years of experience · Team leadership'],
      email: ['Email address', 'you@example.com'],
      phone: ['Phone number', '+966 5x xxx xxxx'],
      link: ['Professional link', 'linkedin.com/in/you'],
      city: ['City, country', 'Riyadh, Saudi Arabia'],
      summary: ['Professional summary', 'Write a concise overview of your experience and professional value...'],
      skills: ['Skills', 'List your skills separated by commas...'],
      languages: ['Languages', 'Arabic — Native\nEnglish — Advanced'],
      projects: ['Projects', 'Project name — your role — outcome...'],
      experience: ['Professional experience', 'Job title — company — period\nAchievements and measurable results...'],
      education: ['Education', 'Degree — university — graduation year...'],
      certificates: ['Professional certificates', 'Certificate — issuer — year...'],
      achievements: ['Awards and achievements', 'Award or achievement — outcome...'],
      volunteer: ['Volunteer work', 'Organization — role — impact...'],
    },
  },
} as const;
