create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (char_length(event_type) between 3 and 80),
  entity_type text check (entity_type is null or char_length(entity_type) between 2 and 40),
  entity_id text check (entity_id is null or char_length(entity_id) <= 160),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_events_user_created_idx
on public.activity_events (user_id, created_at desc);

alter table public.activity_events enable row level security;

drop policy if exists "users_read_own_activity" on public.activity_events;
create policy "users_read_own_activity"
on public.activity_events for select
to authenticated
using (user_id = (select auth.uid()));

revoke insert, update, delete on public.activity_events from anon, authenticated;
grant select on public.activity_events to authenticated;

